# Add file paths for your city boundary, origin blocks, and destinations. Enter False in all fields if data already exists on the SQL database
set_up:
  # for US cities use 4269, NZ cities use 4326, otherwise use whatever the origin blocks has been projected in
  projection: 4326
  # Use a seperate file for each dest type, use the same order as 'services' below
  destination_file_directory:
    - /homedirs/projects/wremo/data/raw/destinations.csv
  # name of column in shapefile to keep for matching with destination data
  dest_id_colname:
    - dest_id
  origin_file_directory: /homedirs/projects/wremo/data/raw/wlg_buildings.shp
orig_id: building_i # SA12018_V1

# Which services do you want to evalaute? (must match 'dest_type' name from destination matix, unless script_mode='setup') TYPE: lst of str's
services:
  - supermarket
  - water
  - EM_hubs
  - health_services
  - fuel_station

# What mode of transport are you evaluating? ['driving', 'walking', 'cycling'] TYPE: str
transport_mode: walking

# What metric would you like to evaluate? comment one out, leaving in list TYPE: str
metric:
  - distance
  - duration

# What percent of CPU cores would you like to utilise? [0.0 - 1.0] TYPE: float
par_frac: 0.8

# What name would save the distance matrix as? TYPE: str
SQL:
  create_db: True
  database_name: wremo # this is the name of the database
  table_name: parcel_distance # this is the name for the table of distances
  port: '5002'
  host: 132.181.102.2
  replace: True


location:
    city: New Zealand
    city_code: nz
    # State code (e.g. 'wa' for Washington, Seattle), this selects the SQL database, 'access_{state}' TYPE: str
    state: nz
    country: nz

# For logging information and downloading the latest OSM data (Check osm_region/osm_subregion for the osm.pbf download link from https://download.geofabrik.de/north-america/us.html) TYPE: str
OSM:
    osm_subregion: new-zealand
    osm_region: australia-oceania
    # where do you want your OSM data saved
    data_directory: /homedirs/man112/osm_data

OSRM:
    host: http://localhost
    port: '6010'
    # Do you want the port closed after use? [True, False] TYPE: bool
    shutdown: True
